=== dandyhorse/course-works/homework_9/src/main/resources/guide.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.epam.com/musicGuide"
        xmlns:g="http://www.epam.com/musicGuide"
        elementFormDefault="qualified">

    <element name="guide" type="g:ArtistList"/>
    <element name="artist" type="g:Artist"/>
    <element name="album" type="g:Album"/>
    <element name="track" type="g:Track"/>
    <element name="albums" type="g:AlbumList"/>

    <complexType name="ArtistList">
        <sequence>
            <element name="artist" type="g:Artist" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="Artist">
        <sequence>
            <element name="albums" type="g:AlbumList" minOccurs="1"/>
        </sequence>
        <attribute name="id" type="unsignedLong" use="required"/>
        <attribute name="name" type="string" use="required"/>
    </complexType>

    <complexType name="AlbumList">
        <sequence minOccurs="1" maxOccurs="unbounded">
            <element name="album" type="g:Album"/>
        </sequence>
    </complexType>

    <complexType name="Album">
        <sequence>
            <element name="track" type="g:Track" minOccurs="1" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="id" type="unsignedLong" use="required"/>
        <attribute name="name" type="string" use="required"/>
        <attribute name="genre" type="string" use="required"/>
    </complexType>

    <complexType name="Track">
        <attribute name="id" type="unsignedLong" use="required"/>
        <attribute name="name" type="string" use="required"/>
        <attribute name="duration" type="duration" use="required"/>
    </complexType>


</schema>

=== dandyhorse/course-works/epam/homework_9/src/main/resources/music_guide.xml
<?xml version="1.0" encoding="UTF-8"?>
<guide xmlns="http://www.epam.com/musicGuide" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.epam.com/musicGuide guide.xsd">

    <artist id="1" name="Sixto Rodriguez">
        <album id="1" title="Cold Fact" genre="Soul">
            <track id="1" title="Sugar Man" duration="PT3M45S"/>
        </album>
    </artist>
    <artist id="2" name="David Bowie">
        <album id="2" title="Heroes" genre="Art Rock">
            <track id="2" title="Life on Mars" duration="PT3M45S"/>
            <track id="3" title="The Man Who Sold the World" duration="PT3M45S"/>
        </album>
        <album id="3" title="Eternal" genre="Doom metal">
            <track id="4" title="Chrono.Naut" duration="PT3M45S"/>
            <track id="5" title="Funeralopolis" duration="PT3M45S"/>
        </album>
    </artist>
    <artist id="3" name="Jimi Hendrix">
        <album id="4" title="Band of Gypsys" genre="Rock">
            <track id="6" title="Who Knows" duration="PT3M45S"/>
            <track id="7" title=" Purple Haze" duration="PT5M45S"/>
        </album>
        <album id="5" title="Eternal" genre="Doom metal">
            <track id="8" title="Chrono.Naut" duration="PT3M45S"/>
            <track id="9" title="Funeralopolis" duration="PT3M45S"/>
        </album>
    </artist>

</guide>
